# Generated by Django 3.2.12 on 2023-02-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questoes',
            new_name='QuestoesModel',
        ),
    ]
